steps:
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build', '-t', 'gcr.io/$PROJECT_ID/donasi-frontend', '.'
    ]

  # Push Docker image ke Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push', 'gcr.io/$PROJECT_ID/donasi-frontend'
    ]

  # Deploy ke App Engine Flex pakai custom runtime
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'app', 'deploy', '--quiet'
    ]

options:
  logging: CLOUD_LOGGING_ONLY
