steps:
  # Install dependencies
  - name: 'gcr.io/cloud-builders/nodejs:20'
    args: ['npm', 'install']

  # Build Next.js
  - name: 'gcr.io/cloud-builders/nodejs:20'
    args: ['npm', 'run', 'build']


  # Replace variable di app.template.yaml jadi app.yaml
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed "s|\${_NEXT_PUBLIC_URL_SERVER}|${_NEXT_PUBLIC_URL_SERVER}|g" app.template.yaml > app.yaml

  # Deploy ke App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'app'
      - 'deploy'
      - '--quiet'

options:
  logging: CLOUD_LOGGING_ONLY
