steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/donasi-frontend', '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/donasi-frontend' ]

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'donasi-frontend'
      - '--image'
      - 'gcr.io/$PROJECT_ID/donasi-frontend'
      - '--region'
      - 'asia-southeast2'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'NEXT_PUBLIC_URL_SERVER=${_NEXT_PUBLIC_URL_SERVER}'

images:
  - 'gcr.io/$PROJECT_ID/donasi-frontend'

options:
  logging: CLOUD_LOGGING_ONLY
