steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']

  # Set environment variables
  - name: 'node:20'
    entrypoint: 'npm'
    env:
      - 'NEXT_PUBLIC_URL_SERVER=${_NEXT_PUBLIC_URL_SERVER}'
    args: ['run', 'build']

  # Deploy ke App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'app'
      - 'deploy'
      - '--quiet'

options:
  logging: CLOUD_LOGGING_ONLY