steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']

  # Build Next.js
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Deploy ke App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'app'
      - 'deploy'
      - '--quiet'
